#! /bin/bash

function extract(){

    local out_directory
    for arg in $@; do
        if [[ $arg == '--create-dir' ]]; then
            out_directory=$(sed -r 's/([^\.])\..*/\1/' <<< $1)
            local i=1

            while [[ -e $out_directory ]]; do
                out_directory=${out_directory}_${i}
                i=$((i+1))
            done

            mkdir -p $out_directory
            shift
            break
        fi
    done

    case $1 in
        *.tar.bz2)
            tar xvjf $1 -C $out_directory
            ;;
        *.tar.gz)
            tar xvzf $1 -C $out_directory
            ;;
        *.bz2)
            tar xvjf $1 -C $out_directory
            ;;
        *.gz)
            tar xvzf $1 -C $out_directory
            ;;
        *.tar)
            tar xvf $1 -C $out_directory
            ;;
        *.tbz2)
            tar xvjf $1 -C $out_directory
            ;;
        *.tgz)
            tar xvzf $1 -C $out_directory
            ;;
        *.zip)
            unzip $1 -d $out_directory
            ;;
        *.rar)
            unrar x $1 $out_directory
            ;;
        *.7z)
            7z x $1 -o${out_directory}
            ;;
        *)
            echo "'$1' cannot be extracted via extract"
            ;;
    esac

    echo "Archive $1 extracted to $out_directory"
}

function check_nb_file(){
    local nb_file=-1
    case $1 in
        *.tar.bz2|*.tar.gz|*.bz2|*.gz|*.tar|*.tbz2|*.tgz)
            nb_file=$(tar tf $1 | cut -d'/' | sort -u | wc -l)
            ;;
        *.zip)
            nb_file=$(zipinfo -l1 $1 | cut -d'/' -f1|sort -u | wc -l)
            ;;
        *.rar)
            nb_file=$(rar lb $1 | cut -d'/' -f1|sort -u | wc -l)
            ;;
        *.7z)
            nb_file=$(7z l $1 |\
                tail -n +21 | head -n -2 |\
                awk '{print $(NF)}' |\
                cut -d'/' -f1 | sort -u | wc -l)
            ;;
        *)
            echo "'$1' cannot be extracted via extract"
            ;;
    esac

    return $nb_file
}
