#! /bin/bash

function extract(){

    local output
    local output_dir
    if [[ $1 == '--create-dir' ]]; then
        shift
        output=$(sed -r 's/([^\.])\..*/\1/' <<< $1)
        output_dir=$output

        local i=1
        while [[ -e $output ]]; do
            output=${output_dir}_${i}
            i=$((i+1))
        done
        output_dir=$output

        mkdir -p $output
    fi

    case $1 in
        *.tar.bz2|*.tar.gz|*.bz2|*.tar|*.tbz2|*.tgz)
            [[ -n $output ]] && \
                tar xvf $1 -C $output || \
                tar xvf $1
            ;;
        *.gz)
            gunzip $1
            ;;
        *.zip)
            [[ -n $output ]] && \
                unzip $1 -d $output ||
                unzip $1
            ;;
        *.7z)
            [[ -n $output ]] && output="-o${output}"
            ;;
        *.rar)
            unrar x $1 $output
            ;;
        *)
            echo "Cannot be extracted, unknown file type '$1'"
            ;;
    esac

    echo "Archive $1 extracted to $output_dir"
}

function check_nb_file(){
    local nb_file=-1
    case $1 in
        *.tar.bz2|*.tar.gz|*.bz2|*.tar|*.tbz2|*.tgz)
            nb_file=$(tar tf $1 | cut -d'/' -f1 | sort -u | wc -l)
            ;;
        *.gz)
            nb_file=1
            ;;
        *.zip)
            nb_file=$(zipinfo -l1 $1 | cut -d'/' -f1 | sort -u | wc -l)
            ;;
        *.rar)
            nb_file=$(rar lb $1 | cut -d'/' -f1 | sort -u | wc -l)
            ;;
        *.7z)
            nb_file=$(7z l $1 |\
                tail -n +21 | head -n -2 |\
                awk '{print $(NF)}' |\
                cut -d'/' -f1 | sort -u | wc -l)
            ;;
        *)
            echo "'$1' cannot be extracted via extract"
            ;;
    esac

    echo $nb_file
}

for archive in $@; do
    if [[ $(check_nb_file $archive) > 1 ]]; then
        extract --create-dir $archive
    else
        extract $archive
    fi
done
